# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.3
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: elvocool@gmail.com
author_name: Elvismutinda
preset_name: starter
project_name: aidWave-frontend

